# site name
prefixName: さくら荘その
siteName: stevessr
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/honjun/cdn@1.8/assets/img/favicon.ico
avatar: https://cdn.aaca.eu.org/api/v1/buckets/bucket1/objects/download?preview=true&prefix=aW1nLzg5NjQ1MzcyLnBuZw==&version_id=4ba1136c-9af9-40d3-b88b-09550aa37810
url: https://sakura.stevessr-github-io.pages.dev
description: Live your life with passion! With some drive!
#cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 0

notice: hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

# 站点菜单配置 【选】
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo },
    转载: {path: /tags/转载/, fa: fa-solid fa-share fa-bounce }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4676574-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp3276802-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4676583-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4676584-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4676590-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/img/109796187_p0.png
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wc1703725-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp1809658-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp2560415-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp2578195-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp3461372-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp3850825-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4041707-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4469633-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4676569-4k-pc-wallpapers.jpg
  - https://mino.firsts1.repl.co:5900/bucket1/4k-pc-wallpapers/wp4676570-4k-pc-wallpapers.jpg


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/499161515, title: Bilibili, desc: 博主的b站视频, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/bilibili.jpg}
  - {url: /, title: stevessr, desc: 一堆垃圾, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/stevessr, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png}
  sina: {url: https://weibo.com/u/7852531849, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/sina.png}
  zhihu: {url: https://www.zhihu.com/people/35-78-68-35, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/zhihu.png}
  email: {url: mailto:steve-ssr@outlook.com, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg}

# 社交按钮(msocial)  url, img 移动端配置 【改】
msocial:
  github: {url: http://github.com/stevessr, fa: fa-github, color: 333}

donate:
  paypal: https://cdn.aaca.eu.org/api/v1/buckets/bucket1/objects/download?preview=true&prefix=aW1nLzg5NjQ1MzcyLnBuZw==&version_id=4ba1136c-9af9-40d3-b88b-09550aa37810 #https://www.paypal.me/hojuncn
  alipay: https://cdn.aaca.eu.org/api/v1/buckets/bucket1/objects/download?preview=true&prefix=aW1nLzg5NjQ1MzcyLnBuZw==&version_id=4ba1136c-9af9-40d3-b88b-09550aa37810 #/img/custom/donate/AliPayQR.jpg
  wechat: https://cdn.aaca.eu.org/api/v1/buckets/bucket1/objects/download?preview=true&prefix=aW1nLzg5NjQ1MzcyLnBuZw==&version_id=4ba1136c-9af9-40d3-b88b-09550aa37810 #/img/custom/donate/WeChanQR.jpg
  wechatSQ: https://cdn.aaca.eu.org/api/v1/buckets/bucket1/objects/download?preview=true&prefix=aW1nLzg5NjQ1MzcyLnBuZw==&version_id=4ba1136c-9af9-40d3-b88b-09550aa37810 #/img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
#valine: true
#v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
#v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

# Waline
waline:
  enable: true
  serverURL: https://waline.alis-st.repl.co #服务端地址
  visitor: true #统计阅读量
  comment_count: true #统计评论数
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 祝开开心心！ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画