# workflow name
name: actions single

# 当有 push 到仓库和外部触发的时候就运行
#on: 
#  push:
#    branches:["blogs"]
##    branches:["main"]
#  pull_request:
#    branches:["main"]
#    branches:["blogs"]

jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      #安装依赖
      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install


      # 生成可访问的文档
      - name: hexo generate
        run: |
          hexo g

      # 生成pages且推送到文件仓库 from https://github.com/peaceiris/actions-gh-pages
      - name: Deploy hexo to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.YUQUE_GIT_HEXO }} # 此处为 hexo-deploy-key
          external_repository: stevessr/stevessr.github.io
          publish_branch: master
          publish_dir: ./public
          commit_message: deploy githubPage
          # commit_message: ${{ github.event.head_commit.message }}